Lab 3/Lab3/Lab3/Models/Friend.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lab3.Models
{
    public class Friend
    {
        [Required]
        [Range(0,200)]
        public int Id { get; set; }
        [Required]
        public string Ime { get; set; }
        [Required]
        public string MestoZiveenje { get; set; }
    }
}

Lab 3/Lab3/Lab3/Controllers/FriendController.cs
using Lab3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab3.Controllers
{
    public class FriendController : Controller
    {
        private static List<Friend> friends = new List<Friend>()
        {
            new Friend(){ Id = 0, Ime = "Example Exampleson", MestoZiveenje = "Example street 0"}
        };

        // GET: Friend
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ShowAllFriends()
        {
            return View(friends);
        }
        public ActionResult NewFriend()
        {
            Friend model = new Friend();
            return View(model);
        }
        [HttpPost]
        public ActionResult InsertNewFriend(Friend model)
        {
            if (!ModelState.IsValid)
            {
                return View("NewFriend", model);
            }
            friends.Add(model);
            return View("ShowAllFriends", friends);
        }

        public ActionResult EditFriend(int id)
        {
            var model = friends.ElementAt(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult EditFriend(Friend model)
        {
            if (!ModelState.IsValid)
            {
                return View("EditFriend", model);
            }
            var forUpdate = friends.ElementAt(model.Id);
            forUpdate.Ime = model.Ime;
            forUpdate.MestoZiveenje = model.MestoZiveenje;
            return View("ShowAllFriends", friends);
        }

        public ActionResult DeleteFriend(int id)
        {
            friends.RemoveAt(id);
            return View("ShowAllFriends", friends);
        }
    }
}

Lab 3/Lab3/Lab3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lab 3/Lab3/Lab3/Views/Friend/EditFriend.cshtml
@model Lab3.Models.Friend

@{
    ViewBag.Title = "EditFriend";
}

<h2>Edit Friend</h2>


@using (Html.BeginForm("EditFriend", "Friend"))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MestoZiveenje, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MestoZiveenje, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MestoZiveenje, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Update" class="btn btn-default" />
            <form>
                <input type="button" value="Back" class="btn btn-default" onclick="window.location.href='/Friend/ShowAllFriends'" />
            </form>
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lab 3/Lab3/Lab3/Views/Friend/NewFriend.cshtml
@model Lab3.Models.Friend

@{
    ViewBag.Title = "NewFriend";
}

<h2>NewFriend</h2>


@using (Html.BeginForm("InsertNewFriend", "Friend")) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MestoZiveenje, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MestoZiveenje, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MestoZiveenje, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="btn btn-default" />
            <form>
                <input type="button" value="Back" class="btn btn-default" onclick="window.location.href='/Friend/ShowAllFriends'"/>
            </form>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "ShowAllFriends")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lab 3/Lab3/Lab3/Views/Friend/ShowAllFriends.cshtml
@model List<Lab3.Models.Friend>

@{
    ViewBag.Title = "AllFriends";
}

<h2>All Friends</h2>

<table style="border: 2px solid; text-align: center">
    <tr style="border: 2px solid">
        <th style="width: 100px; border-right: 2px solid; text-align: center">
            Friend ID.
        </th>

        <th style="width: 200px; border-right: 2px solid; text-align: center">
            Friend Name
        </th>

        <th  style="width: 300px; border-right: 2px solid; text-align: center">
            Place
        </th>

        <th  style="width: 150px; text-align: center">
            Tools
        </th>
    </tr>
    @{
        int i = 0;
        foreach (var friend in Model)
        {
        <tr>
            <td style="border-right: 2px solid">
                @friend.Id
            </td>

            <td style="border-right: 2px solid">
                @friend.Ime
            </td>

            <td style="border-right: 2px solid">
                @friend.MestoZiveenje
            </td>

            <td>
                @Html.ActionLink("Edit", "EditFriend", new { id = i }) |
                @Html.ActionLink("Delete", "DeleteFriend", new { id = i })
            </td>
        </tr>
            i++;
        }
    }
</table>

Lab 3/Lab3/Lab3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Lab 3/Lab3/Lab3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lab 3/Lab3/Lab3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Lab 3/Lab3/Lab3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("All Friends", "ShowAllFriends", "Friend")</li>
                    <li>@Html.ActionLink("Add Friend", "NewFriend", "Friend")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>